name: CI
on:
  push:
  schedule:
    - cron: '0 8 * * 1' # Weekly on Monday 08:00

jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1', '3.2', truffleruby-head ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: git config user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - run: git remote add upstream https://github.com/gettalong/hexapdf.git
    - run: git fetch upstream
    - run: git merge upstream/master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: sudo apt install netpbm pngcheck
    - run: bundle exec rake test
      env:
        NO_SIMPLECOV: true
